name=Hobot-S-Arduino-Lib
version=1.0
author=MES <Mes.billing@yandex.ru>
maintainer=MES <Mes.billing@yandex.ru>
sentence=API for the Hobot S Hub Large
paragraph=Implements interaction with the main board
category=Other
url=https://github.com/mes-sts/MES-Arduino-Libs
architectures=stm32
includes=HobotS.h
